# Build

ARG VITE_SERVER_URL
ARG VITE_ENDPOINT_LOGIN
ARG VITE_ENDPOINT_REGISTER
ARG VITE_ENDPOINT_GET_PRODUCTS
ARG VITE_ENDPOINT_GET_PRODUCT
ARG VITE_ENDPOINT_CREATE_PRODUCT
ARG VITE_ENDPOINT_UPDATE_PRODUCT
ARG VITE_ENDPOINT_DELETE_PRODUCT
ARG VITE_ENDPOINT_GET_ORDERS
ARG VITE_ENDPOINT_BUY
ARG VITE_ENDPOINT_FORGOT_PASSWORD
ARG VITE_ENDPOINT_RESET_PASSWORD
ARG VITE_ENDPOINT_GET_STORE
ARG VITE_ENDPOINT_CREATE_STORE
ARG VITE_ENDPOINT_GET_USER
ARG VITE_ENDPOINT_UPDATE_USER
ARG VITE_ENDPOINT_GET_CART
ARG VITE_ENDPOINT_ADD_ITEM
ARG VITE_ENDPOINT_DELETE_ITEM
ARG VITE_ENDPOINT_BUY_CART
ARG VITE_ENDPOINT_UPDATE_ITEM


ENV VITE_SERVER_URL=${VITE_SERVER_URL}
ENV VITE_ENDPOINT_LOGIN=${VITE_ENDPOINT_LOGIN}
ENV VITE_ENDPOINT_REGISTER=${VITE_ENDPOINT_REGISTER}
ENV VITE_ENDPOINT_GET_PRODUCTS=${VITE_ENDPOINT_GET_PRODUCTS}
ENV VITE_ENDPOINT_GET_PRODUCT=${VITE_ENDPOINT_GET_PRODUCT}
ENV VITE_ENDPOINT_CREATE_PRODUCT=${VITE_ENDPOINT_CREATE_PRODUCT}
ENV VITE_ENDPOINT_UPDATE_PRODUCT=${VITE_ENDPOINT_UPDATE_PRODUCT}
ENV VITE_ENDPOINT_DELETE_PRODUCT=${VITE_ENDPOINT_DELETE_PRODUCT}
ENV VITE_ENDPOINT_GET_ORDERS=${VITE_ENDPOINT_GET_ORDERS}
ENV VITE_ENDPOINT_BUY=${VITE_ENDPOINT_BUY}
ENV VITE_ENDPOINT_FORGOT_PASSWORD=${VITE_ENDPOINT_FORGOT_PASSWORD}
ENV VITE_ENDPOINT_RESET_PASSWORD=${VITE_ENDPOINT_RESET_PASSWORD}
ENV VITE_ENDPOINT_GET_STORE=${VITE_ENDPOINT_GET_STORE}
ENV VITE_ENDPOINT_CREATE_STORE=${VITE_ENDPOINT_CREATE_STORE}
ENV VITE_ENDPOINT_GET_USER=${VITE_ENDPOINT_GET_USER}
ENV VITE_ENDPOINT_UPDATE_USER=${VITE_ENDPOINT_UPDATE_USER}
ENV VITE_ENDPOINT_GET_CART=${VITE_ENDPOINT_GET_CART}
ENV VITE_ENDPOINT_ADD_ITEM=${VITE_ENDPOINT_ADD_ITEM}
ENV VITE_ENDPOINT_DELETE_ITEM=${VITE_ENDPOINT_DELETE_ITEM}
ENV VITE_ENDPOINT_BUY_CART=${VITE_ENDPOINT_BUY_CART}
ENV VITE_ENDPOINT_UPDATE_ITEM=${VITE_ENDPOINT_UPDATE_ITEM}


FROM node:20.2.0-alpine3.17 as build
WORKDIR /app
COPY . .
RUN npm ci
RUN npm run build



# Run
FROM nginx:stable-alpine3.17 as production



ARG VITE_SERVER_URL
ARG VITE_ENDPOINT_LOGIN
ARG VITE_ENDPOINT_REGISTER
ARG VITE_ENDPOINT_GET_PRODUCTS
ARG VITE_ENDPOINT_GET_PRODUCT
ARG VITE_ENDPOINT_CREATE_PRODUCT
ARG VITE_ENDPOINT_UPDATE_PRODUCT
ARG VITE_ENDPOINT_DELETE_PRODUCT
ARG VITE_ENDPOINT_GET_ORDERS
ARG VITE_ENDPOINT_BUY
ARG VITE_ENDPOINT_FORGOT_PASSWORD
ARG VITE_ENDPOINT_RESET_PASSWORD
ARG VITE_ENDPOINT_GET_STORE
ARG VITE_ENDPOINT_CREATE_STORE
ARG VITE_ENDPOINT_GET_USER
ARG VITE_ENDPOINT_UPDATE_USER
ARG VITE_ENDPOINT_GET_CART
ARG VITE_ENDPOINT_ADD_ITEM
ARG VITE_ENDPOINT_DELETE_ITEM
ARG VITE_ENDPOINT_BUY_CART
ARG VITE_ENDPOINT_UPDATE_ITEM

ENV NODE_ENV production

ENV VITE_SERVER_URL=${VITE_SERVER_URL}
ENV VITE_ENDPOINT_LOGIN=${VITE_ENDPOINT_LOGIN}
ENV VITE_ENDPOINT_REGISTER=${VITE_ENDPOINT_REGISTER}
ENV VITE_ENDPOINT_GET_PRODUCTS=${VITE_ENDPOINT_GET_PRODUCTS}
ENV VITE_ENDPOINT_GET_PRODUCT=${VITE_ENDPOINT_GET_PRODUCT}
ENV VITE_ENDPOINT_CREATE_PRODUCT=${VITE_ENDPOINT_CREATE_PRODUCT}
ENV VITE_ENDPOINT_UPDATE_PRODUCT=${VITE_ENDPOINT_UPDATE_PRODUCT}
ENV VITE_ENDPOINT_DELETE_PRODUCT=${VITE_ENDPOINT_DELETE_PRODUCT}
ENV VITE_ENDPOINT_GET_ORDERS=${VITE_ENDPOINT_GET_ORDERS}
ENV VITE_ENDPOINT_BUY=${VITE_ENDPOINT_BUY}
ENV VITE_ENDPOINT_FORGOT_PASSWORD=${VITE_ENDPOINT_FORGOT_PASSWORD}
ENV VITE_ENDPOINT_RESET_PASSWORD=${VITE_ENDPOINT_RESET_PASSWORD}
ENV VITE_ENDPOINT_GET_STORE=${VITE_ENDPOINT_GET_STORE}
ENV VITE_ENDPOINT_CREATE_STORE=${VITE_ENDPOINT_CREATE_STORE}
ENV VITE_ENDPOINT_GET_USER=${VITE_ENDPOINT_GET_USER}
ENV VITE_ENDPOINT_UPDATE_USER=${VITE_ENDPOINT_UPDATE_USER}
ENV VITE_ENDPOINT_GET_CART=${VITE_ENDPOINT_GET_CART}
ENV VITE_ENDPOINT_ADD_ITEM=${VITE_ENDPOINT_ADD_ITEM}
ENV VITE_ENDPOINT_DELETE_ITEM=${VITE_ENDPOINT_DELETE_ITEM}
ENV VITE_ENDPOINT_BUY_CART=${VITE_ENDPOINT_BUY_CART}
ENV VITE_ENDPOINT_UPDATE_ITEM=${VITE_ENDPOINT_UPDATE_ITEM}







COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
