name: Docker Build & Publish

on:
  push:
    branches:
      - dev

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: psiquedelos/is2_front:latest

    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Clone GitHub repository
      run: git clone https://github.com/AgrimarketUN/AWS-Terraform-Pipeline.git

    - name: Move Docker image to GitHub repository
      run: mv ./psiquedelos/is2_front:latest ./AWS-Terraform-Pipeline

    - name: Commit and push changes to GitHub repository
      run: |
        cd AWS-Terraform-Pipeline
        git add .
        git commit -m "Add Docker image"
        git push
