name: Docker Build & Publish to Docker Hub & Push to GitHub Frontend

on:
  push:
    branches:
      - docker_test

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: psiquedelos/is2_back:latest

    - name: Configure SSH key
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Clone GitHub repository
      run: git clone git@github.com:AgrimarketUN/AWS-Terraform-Pipeline.git

    - name: Configurar identidad de usuario en Git
      run: |
        cd AWS-Terraform-Pipeline
        git config user.email "dmirandam@unal.edu.co"
        git config user.name "dmirandam"

    - name: Create File
      run: |
        cd AWS-Terraform-Pipeline
        caracteres="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
        longitud=8
        nombre_aleatorio=$(cat /dev/urandom | tr -dc "$caracteres" | fold -w "$longitud" | head -n 1)
        fecha_hora=$(date +"%Y-%m-%d %H:%M:%S")
        echo -e "$fecha_hora\nfront" > "$nombre_aleatorio"
        ls -al
        git init
        git status

    - name: Commit to GitHub repository
      run: | 
        cd AWS-Terraform-Pipeline
        git add .
        git commit -m "Add Docker image"

    - name: Push changes to GitHub repository
      run: |
        cd AWS-Terraform-Pipeline
        git push
