name: Docker Build & Publish to Docker Hub & Push to GitHub Frontend

on:
  push:
    branches:
      - docker_test

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
    - name: Create File
      run: |
        touch archivo_$(date +%Y-%m-%d)



