name: Docker Build & Publish to Docker Hub & Push to GitHub Frontend

on:
  push:
    branches:
      - docker_test

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
    - name: Create File
      run: |
        caracteres="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
        longitud=8
        nombre_aleatorio=$(cat /dev/urandom | tr -dc "$caracteres" | fold -w "$longitud" | head -n 1)
        fecha_hora=$(date +"%Y-%m-%d %H:%M:%S")
        echo -e "$fecha_hora\nfront" > "$nombre_aleatorio"
        ls -al


