name: Docker Build & Publish to Docker Hub & Push to GitHub Frontend

on:
  push:
    branches:
      - docker_test

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
    - name: Create File
      run: |
        nombre_aleatorio=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 10 | head -n 1)
        touch "$nombre_aleatorio"
        ls -al


