name: Docker Build & Publish

on:
  push:
    branches:
      - docker_test

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
    # - name: Checkout repository
    #   uses: actions/checkout@v2

    # - name: Login to Docker Hub
    #   uses: docker/login-action@v1
    #   with:
    #     username: 

    # - name: Build and push Docker image
    #   uses: docker/build-push-action@v2
    #   with:
    #     context: .
    #     push: true
    #     tags: psiquedelos/is2_front:latest

    - name: Configure Git
      run: |
        git config --global user.name "dmirandam"
        git config --global user.email "dmirandam@unal.edu.co"

    - name: Clone GitHub repository
      run: git clone https://github.com/AgrimarketUN/AWS-Terraform-Pipeline.git

    - name: Create File
      run: |
        pwd
        touch "a"

    - name: Commit to GitHub repository
      run: |   
        git add .
        git commit -m "Add Docker image"

    - name: push changes to GitHub repository
      run: git push https://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@github.com/AgrimarketUN/AWS-Terraform-Pipeline.git
